/* =========================
   UI / ONLINE / TOURNAMENT
   ========================= */
function avatarFallback(name){const ch=encodeURIComponent((String(name||'P').trim()[0]||'P').toUpperCase());return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="#6b451d"/><text x="50" y="66" text-anchor="middle" font-size="52" fill="#ffe27c" font-family="Arial">${decodeURIComponent(ch)}</text></svg>`)}`}
function chooseTime(kind,playerId=null){openModal(`<h3>⏱️ ဘယ်အချိန်နဲ့ ကစားမလဲ?</h3><p>${kind==='quick'?'Online Quick Match':kind==='invite'?'Friend Match':'Computer Pro'} အတွက် တစ်ယောက်စီအချိန်ရွေးပါ</p><div class="grid">${[1,2,3,5,10].map(m=>`<button class="btn secondary" onclick="closeModal();startWithTime('${kind}',${m},${playerId?`'${playerId}'`:'null'})">${m} မိနစ်</button>`).join('')}</div>`)}
function startWithTime(kind,m,playerId=null){Game.minutes=m;if(kind==='ai')return Game.start('ai',{minutes:m});if(kind==='quick')return startQuickMatch(m);if(kind==='invite')return sendGameInvite(playerId,m*60)}
function startAI(){chooseTime('ai')}
async function retryOnlineConnection(){$("authState").className="notice";$("authState").innerHTML='<span class="spinner"></span>Online Server ပြန်ချိတ်နေပါတယ်...';await Backend.init();if(Backend.ready){toast("Online Server ချိတ်ဆက်ပြီးပါပြီ");startLobbyLoop()}}
async function resumeActiveGame(){try{await Backend.resume()}catch(e){toast(humanError(e.code||e.message))}}
async function startQuickMatch(minutes=5){Game.minutes=Number(minutes)||5;if(Backend.activeGameId){await resumeActiveGame();return}if(!Backend.ready){$("onlineInfo").innerHTML='<span class="spinner"></span>Online Server ကို ချိတ်ဆက်နေပါတယ်...';await Backend.init();if(!Backend.ready){openModal(`<h3>🌐 Online Server မချိတ်နိုင်သေးပါ</h3><p>${esc(Backend.authError||"Connection မအောင်မြင်ပါ")}</p><button class="btn green" onclick="closeModal();retryOnlineConnection()">↻ Online ပြန်ချိတ်မယ်</button>`);return}}const token=++Backend.quickToken,btn=$("quickMatchBtn"),deadline=Date.now()+7000;btn.disabled=true;$("onlineInfo").innerHTML='<span class="spinner"></span>လူကစားသမားကို Online မှာ ရှာနေပါတယ်...';loadLobby();try{while(token===Backend.quickToken&&Date.now()<deadline){const r=await Backend.api("matchmake",{time_limit_seconds:Game.minutes*60});loadLobby();if(r.match?.status==="matched"&&r.game){btn.disabled=false;$("onlineInfo").textContent="✅ Online လူကစားသမားနဲ့ Match ဖြစ်ပါပြီ";await Backend.openGame(r.game);return}const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));$("onlineInfo").textContent=`⚡ လူရှာနေပါတယ်... ${left} sec`;await sleep(1100)}if(token!==Backend.quickToken)return;await Backend.api("cancel_matchmake").catch(()=>{});loadLobby();const raced=await Backend.checkActiveGame(false);if(raced){btn.disabled=false;$("onlineInfo").textContent="✅ Online Match ဖြစ်ပါပြီ";await Backend.openGame(raced);return}btn.disabled=false;$("onlineInfo").textContent="🤖 Online လူမတွေ့သေးလို့ Computer Pro နဲ့ စတင်လိုက်ပါတယ်";Backend.activeGameId=null;Game.start("bot_fallback",{minutes:Game.minutes})}catch(e){btn.disabled=false;await Backend.api("cancel_matchmake").catch(()=>{});loadLobby();$("onlineInfo").textContent="❌ Online Matchmaking Error: "+humanError(e.code||e.message);toast(humanError(e.code||e.message))}}
let replayState={boards:[],moves:[],index:0};
function initialReplayBoard(){return Rules.initial()}
async function openMoveReplay(){try{let boards=[],labels=[];if(Game.mode==='online'){const r=await Backend.social('history',{game_id:Game.matchId}),moves=r.moves||[];boards=[initialReplayBoard(),...moves.map(m=>cloneBoard(m.board_after))];labels=moves.map(m=>`${m.move_number}. ${m.color===1?'Black':'White'}: ${(m.path||[]).map(x=>squareName(x.from)+(x.capture?'x':'-')+squareName(x.to)).join(' → ')}`)}else{boards=[initialReplayBoard(),...Game.snapshots.map(cloneBoard)];labels=Game.history.slice()}replayState={boards,moves:labels,index:Math.max(0,boards.length-1)};showScreen('replay');renderReplay()}catch(e){toast(humanError(e.code||e.message))}}
function setReplayIndex(i){replayState.index=Math.max(0,Math.min(i,replayState.boards.length-1));renderReplay()}
function replayStep(d){setReplayIndex(replayState.index+d)}
function renderReplay(){const b=replayState.boards[replayState.index]||initialReplayBoard(),el=$("replayBoard");el.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const sq=document.createElement('div');sq.className='square '+(((r+c)%2)?'dark':'light');const p=b[r][c];if(p){const pe=document.createElement('div');pe.className='piece '+(p>0?'black':'white')+(isKing(p)?' king':'');if(isKing(p)){const k=document.createElement('span');k.className='kingmark';k.textContent='♛';pe.appendChild(k)}sq.appendChild(pe)}el.appendChild(sq)}$("replayRange").max=Math.max(0,replayState.boards.length-1);$("replayRange").value=replayState.index;$("replayInfo").textContent=replayState.index===0?'ပွဲစတင်အနေအထား':(replayState.moves[replayState.index-1]||`Move ${replayState.index}`)}
function closeReplay(){showScreen(spectateGameId?'spectate':'game')}
async function resignGame(){if(Game.result.done)return;if(Game.mode==="online"){openModal(`<h3>🏳 Resign လုပ်မလား?</h3><p>Online result မှာ ရှုံးပွဲအဖြစ် အတည်ပြုမယ်။</p><button class="btn red" onclick="closeModal();confirmOnlineResign()">Resign</button>`);return}openModal(`<h3>🏳 Resign လုပ်မလား?</h3><p>Resign လုပ်ရင် ချက်ချင်းရှုံးပါမယ်။</p><button class="btn red" onclick="closeModal();Game.finish({winner:${Game.mode==='local2p'?-Game.turn:-Game.mySide},reason:'resign'})">Resign</button>`)}
async function confirmOnlineResign(){try{const r=await Backend.api("resign",{game_id:Game.matchId});Game.applyServerGame(r.game)}catch(e){toast(humanError(e.code||e.message))}}
async function offerDraw(){if(Game.result.done)return;if(Game.mode==="ai"||Game.mode==="bot_fallback"){toast("Computer match မှာ Draw offer မသုံးပါ");return}if(Game.serverGame?.mode==="tournament"){toast("Tournament ပွဲမှာ Draw မခွင့်ပြုပါ");return}try{const r=await Backend.api("draw",{game_id:Game.matchId});Game.applyServerGame(r.game);if(r.game.status==="active"&&r.game.draw_offer_by===Backend.user.id)toast("Draw Offer ပို့ပြီးပါပြီ") }catch(e){toast(humanError(e.code||e.message))}}
async function acceptOnlineDraw(){return offerDraw()}
async function rejectOnlineDraw(){try{const r=await Backend.api("reject_draw",{game_id:Game.matchId});Game.lastDrawOffer=null;Game.applyServerGame(r.game);toast("Draw Offer ကို ပယ်ချလိုက်ပါတယ်")}catch(e){toast(humanError(e.code||e.message))}}
async function openHistory(){return openMoveReplay()}
function leaveToHome(){closeModal();if(Game.mode==="online"&&!Game.result.done){showScreen("home");$("resumeCard").classList.remove("hidden");toast("Online ပွဲက ဆက်လည်နေပါတယ် · Resume လုပ်နိုင်ပါတယ်");return}Game.__aiToken=null;Game.aiBusy=false;Game.timer.stop();showScreen("home")}
function goHome(){clearInterval(dmTimer);dmTimer=null;currentDMPlayer=null;Backend.stopTournamentWatch();showScreen("home");Backend.checkActiveGame(false);Backend.loadProfile().catch(()=>{});startLobbyLoop()}
function showRules(){openModal(`<h3>📖 Rules</h3><div class="notice">Capture ရှိရင် မဖြစ်မနေစားရမယ်။ Capture လမ်းကြောင်းများရှိရင် အများဆုံးအရုပ်စားနိုင်တဲ့လမ်းကိုရွေးမယ်။ စားရမယ့်အရေအတွက်တူရင် ကြိုက်တဲ့လမ်းကိုရွေးနိုင်ပါတယ်။ သာမန်ကျားက ထိပ်ဆုံးရောက်ပြီး King ဖြစ်သွားတဲ့အချိန်မှာ အဲဒီအလှည့်ကို ချက်ချင်းရပ်ပြီး ပြိုင်ဘက်အလှည့်ပြောင်းရပါမယ်။ Pieces မရှိတော့ခြင်း၊ legal move မရှိခြင်း၊ အချိန်ကုန်ခြင်း၊ Resign လုပ်ခြင်းနဲ့ reconnect grace ကျော်ခြင်းတို့သည် အရှုံးဖြစ်ပါတယ်။ Online move/result ကို Server Rule Engine က အတည်ပြုပါတယ်။</div>`)}
let lobbyTimer=null,inviteTimer=null,currentDMPlayer=null,dmTimer=null,spectateTimer=null,spectateGameId=null,gameChatTimer=null;
