/* =========================
   UI / ONLINE / TOURNAMENT
   ========================= */
function avatarFallback(name){const ch=encodeURIComponent((String(name||'P').trim()[0]||'P').toUpperCase());return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="#6b451d"/><text x="50" y="66" text-anchor="middle" font-size="52" fill="#ffe27c" font-family="Arial">${decodeURIComponent(ch)}</text></svg>`)}`}
function chooseTime(kind,playerId=null){openModal(`<h3>⏱️ ဘယ်အချိန်နဲ့ ကစားမလဲ?</h3><p>${kind==='quick'?'Online Quick Match':kind==='invite'?'Friend Match':'Computer Pro'} အတွက် တစ်ယောက်စီအချိန်ရွေးပါ</p><div class="grid">${[1,2,3,5,10].map(m=>`<button class="btn secondary" onclick="closeModal();startWithTime('${kind}',${m},${playerId?`'${playerId}'`:'null'})">${m} မိနစ်</button>`).join('')}</div>`)}
function startWithTime(kind,m,playerId=null){Game.minutes=m;if(kind==='ai')return Game.start('ai',{minutes:m});if(kind==='quick')return startQuickMatch(m);if(kind==='invite')return sendGameInvite(playerId,m*60)}
function startAI(){chooseTime('ai')}
async function retryOnlineConnection(){$("authState").className="notice";$("authState").innerHTML='<span class="spinner"></span>Online Server ပြန်ချိတ်နေပါတယ်...';await Backend.init();if(Backend.ready){toast("Online Server ချိတ်ဆက်ပြီးပါပြီ");startLobbyLoop()}}
async function resumeActiveGame(){try{await Backend.resume()}catch(e){toast(humanError(e.code||e.message))}}
async function startQuickMatch(minutes=5){Game.minutes=Number(minutes)||5;if(Backend.activeGameId){await resumeActiveGame();return}if(!Backend.ready){$("onlineInfo").innerHTML='<span class="spinner"></span>Online Server ကို ချိတ်ဆက်နေပါတယ်...';await Backend.init();if(!Backend.ready){openModal(`<h3>🌐 Online Server မချိတ်နိုင်သေးပါ</h3><p>${esc(Backend.authError||"Connection မအောင်မြင်ပါ")}</p><button class="btn green" onclick="closeModal();retryOnlineConnection()">↻ Online ပြန်ချိတ်မယ်</button>`);return}}const token=++Backend.quickToken,btn=$("quickMatchBtn"),deadline=Date.now()+7000;btn.disabled=true;$("onlineInfo").innerHTML='<span class="spinner"></span>လူကစားသမားကို Online မှာ ရှာနေပါတယ်...';loadLobby();try{while(token===Backend.quickToken&&Date.now()<deadline){const r=await Backend.api("matchmake",{time_limit_seconds:Game.minutes*60});loadLobby();if(r.match?.status==="matched"&&r.game){btn.disabled=false;$("onlineInfo").textContent="✅ Online လူကစားသမားနဲ့ Match ဖြစ်ပါပြီ";await Backend.openGame(r.game);return}const left=Math.max(0,Math.ceil((deadline-Date.now())/1000));$("onlineInfo").textContent=`⚡ လူရှာနေပါတယ်... ${left} sec`;await sleep(1100)}if(token!==Backend.quickToken)return;await Backend.api("cancel_matchmake").catch(()=>{});loadLobby();const raced=await Backend.checkActiveGame(false);if(raced){btn.disabled=false;$("onlineInfo").textContent="✅ Online Match ဖြစ်ပါပြီ";await Backend.openGame(raced);return}btn.disabled=false;$("onlineInfo").textContent="🤖 Online လူမတွေ့သေးလို့ Computer Pro နဲ့ စတင်လိုက်ပါတယ်";Backend.activeGameId=null;Game.start("bot_fallback",{minutes:Game.minutes})}catch(e){btn.disabled=false;await Backend.api("cancel_matchmake").catch(()=>{});loadLobby();$("onlineInfo").textContent="❌ Online Matchmaking Error: "+humanError(e.code||e.message);toast(humanError(e.code||e.message))}}
let replayState={boards:[],moves:[],index:0};
function initialReplayBoard(){return Rules.initial()}
async function openMoveReplay(){try{let boards=[],labels=[];if(Game.mode==='online'){const r=await Backend.social('history',{game_id:Game.matchId}),moves=r.moves||[];boards=[initialReplayBoard(),...moves.map(m=>cloneBoard(m.board_after))];labels=moves.map(m=>`${m.move_number}. ${m.color===1?'Black':'White'}: ${(m.path||[]).map(x=>squareName(x.from)+(x.capture?'x':'-')+squareName(x.to)).join(' → ')}`)}else{boards=[initialReplayBoard(),...Game.snapshots.map(cloneBoard)];labels=Game.history.slice()}replayState={boards,moves:labels,index:Math.max(0,boards.length-1)};showScreen('replay');renderReplay()}catch(e){toast(humanError(e.code||e.message))}}
function setReplayIndex(i){replayState.index=Math.max(0,Math.min(i,replayState.boards.length-1));renderReplay()}
function replayStep(d){setReplayIndex(replayState.index+d)}
function renderReplay(){const b=replayState.boards[replayState.index]||initialReplayBoard(),el=$("replayBoard");el.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const sq=document.createElement('div');sq.className='square '+(((r+c)%2)?'dark':'light');const p=b[r][c];if(p){const pe=document.createElement('div');pe.className='piece '+(p>0?'black':'white')+(isKing(p)?' king':'');if(isKing(p)){const k=document.createElement('span');k.className='kingmark';k.textContent='♛';pe.appendChild(k)}sq.appendChild(pe)}el.appendChild(sq)}$("replayRange").max=Math.max(0,replayState.boards.length-1);$("replayRange").value=replayState.index;$("replayInfo").textContent=replayState.index===0?'ပွဲစတင်အနေအထား':(replayState.moves[replayState.index-1]||`Move ${replayState.index}`)}
function closeReplay(){showScreen(spectateGameId?'spectate':'game')}
async function resignGame(){if(Game.result.done)return;if(Game.mode==="online"){openModal(`<h3>🏳 Resign လုပ်မလား?</h3><p>Online result မှာ ရှုံးပွဲအဖြစ် အတည်ပြုမယ်။</p><button class="btn red" onclick="closeModal();confirmOnlineResign()">Resign</button>`);return}openModal(`<h3>🏳 Resign လုပ်မလား?</h3><p>Resign လုပ်ရင် ချက်ချင်းရှုံးပါမယ်။</p><button class="btn red" onclick="closeModal();Game.finish({winner:${Game.mode==='local2p'?-Game.turn:-Game.mySide},reason:'resign'})">Resign</button>`)}
async function confirmOnlineResign(){try{const r=await Backend.api("resign",{game_id:Game.matchId});Game.applyServerGame(r.game)}catch(e){toast(humanError(e.code||e.message))}}
async function offerDraw(){if(Game.result.done)return;if(Game.mode==="ai"||Game.mode==="bot_fallback"){toast("Computer match မှာ Draw offer မသုံးပါ");return}if(Game.serverGame?.mode==="tournament"){toast("Tournament ပွဲမှာ Draw မခွင့်ပြုပါ");return}try{const r=await Backend.api("draw",{game_id:Game.matchId});Game.applyServerGame(r.game);if(r.game.status==="active"&&r.game.draw_offer_by===Backend.user.id)toast("Draw Offer ပို့ပြီးပါပြီ") }catch(e){toast(humanError(e.code||e.message))}}
async function acceptOnlineDraw(){return offerDraw()}
async function rejectOnlineDraw(){try{const r=await Backend.api("reject_draw",{game_id:Game.matchId});Game.lastDrawOffer=null;Game.applyServerGame(r.game);toast("Draw Offer ကို ပယ်ချလိုက်ပါတယ်")}catch(e){toast(humanError(e.code||e.message))}}
async function openHistory(){return openMoveReplay()}
function leaveToHome(){closeModal();if(Game.mode==="online"&&!Game.result.done){showScreen("home");$("resumeCard").classList.remove("hidden");toast("Online ပွဲက ဆက်လည်နေပါတယ် · Resume လုပ်နိုင်ပါတယ်");return}Game.__aiToken=null;Game.aiBusy=false;Game.timer.stop();showScreen("home")}
function goHome(){clearInterval(dmTimer);dmTimer=null;currentDMPlayer=null;Backend.stopTournamentWatch();showScreen("home");Backend.checkActiveGame(false);Backend.loadProfile().catch(()=>{});startLobbyLoop()}
function showRules(){openModal(`<h3>📖 Rules</h3><div class="notice">Capture ရှိရင် မဖြစ်မနေစားရမယ်။ Capture လမ်းကြောင်းများရှိရင် အများဆုံးအရုပ်စားနိုင်တဲ့လမ်းကိုရွေးမယ်။ စားရမယ့်အရေအတွက်တူရင် ကြိုက်တဲ့လမ်းကိုရွေးနိုင်ပါတယ်။ သာမန်ကျားက ထိပ်ဆုံးရောက်ပြီး King ဖြစ်သွားတဲ့အချိန်မှာ အဲဒီအလှည့်ကို ချက်ချင်းရပ်ပြီး ပြိုင်ဘက်အလှည့်ပြောင်းရပါမယ်။ Pieces မရှိတော့ခြင်း၊ legal move မရှိခြင်း၊ အချိန်ကုန်ခြင်း၊ Resign လုပ်ခြင်းနဲ့ reconnect grace ကျော်ခြင်းတို့သည် အရှုံးဖြစ်ပါတယ်။ Online move/result ကို Server Rule Engine က အတည်ပြုပါတယ်။</div>`) }
let lobbyTimer=null,inviteTimer=null,currentDMPlayer=null,dmTimer=null,spectateTimer=null,spectateGameId=null,gameChatTimer=null;
async function loadLobby(){if(!Backend.ready)return;try{const r=await Backend.social('lobby');const w=$("waitingPlayers"),l=$("liveGames");w.innerHTML=(r.waiting||[]).map(x=>`<div class="wait-card person" onclick="openPlayer('${x.user_id}')"><img class="avatar" src="${esc(x.profile?.avatar_url||avatarFallback(x.profile?.username))}"><div class="grow"><b>${esc(x.profile?.username||'Player')}</b><div class="small">Rating ${x.rating} · ${Math.round(x.time_limit_seconds/60)} min နဲ့ စောင့်နေသည်</div></div><span class="pill">WAITING</span></div>`).join('')||'<div class="empty">အခုလောလောဆယ် စောင့်နေသူမရှိသေးပါ</div>';l.innerHTML=(r.live_games||[]).map(g=>`<div class="live-card"><div class="person"><img class="avatar" src="${esc(g.black?.avatar_url||avatarFallback(g.black?.username))}"><div class="grow"><b>${esc(g.black?.username||'Black')} vs ${esc(g.white?.username||'White')}</b><div class="small">${g.mode==='tournament'?'🏆 Tournament':g.mode==='casual'?'🤝 Friend Match':'🌐 Online'} · ${Math.round(g.time_limit_seconds/60)} min · Move ${g.move_number||0}</div></div><button class="btn secondary" style="max-width:88px" onclick="spectateGame('${g.id}')">👁️ ကြည့်မယ်</button></div></div>`).join('')||'<div class="empty">Live ပွဲမရှိသေးပါ</div>'}catch(e){console.warn('lobby',e)}}
function startLobbyLoop(){clearInterval(lobbyTimer);loadLobby();lobbyTimer=setInterval(loadLobby,3000);clearInterval(inviteTimer);loadInvites();inviteTimer=setInterval(loadInvites,4000)}
function stopLobbyLoop(){clearInterval(lobbyTimer);lobbyTimer=null}
async function openMyProfile(){if(!Backend.ready)return toast('Online account မချိတ်ရသေးပါ');showScreen('profile');Backend.renderProfile()}
async function fileData(file){return await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)})}
async function saveProfile(){try{const f=$("profileAvatarFile").files[0];if(f&&f.size>2097152)return toast('ပုံဖိုင် 2MB အောက်ရွေးပါ');const avatar_data=f?await fileData(f):null;const r=await Backend.social('update_profile',{username:$("profileNameInput").value,bio:$("profileBioInput").value,avatar_data});Backend.profile=r.profile;Backend.renderProfile();Backend.startLobbyPresence();toast('ပရိုဖိုင် သိမ်းပြီးပါပြီ')}catch(e){toast(humanError(e.code||e.message))}}
async function openPlayer(id){try{const r=await Backend.social('player',{player_id:id}),p=r.profile,f=r.friendship;let action='';if(id!==Backend.user.id){if(!f)action=`<button class="btn" onclick="friendRequest('${id}')">＋ Friend အပ်မယ်</button>`;else if(f.status==='pending'&&f.addressee_id===Backend.user.id)action=`<button class="btn" onclick="friendAccept('${f.id}')">✓ Friend လက်ခံမယ်</button>`;else if(f.status==='accepted')action=`<div class="grid"><button class="btn secondary" onclick="closeModal();openDM('${id}','${esc(p.username)}')">💬 Message</button><button class="btn" onclick="chooseTime('invite','${id}')">🎮 ကစားဖို့ဖိတ်မယ်</button></div>`}openModal(`<div class="profile-head"><img class="avatar big" src="${esc(p.avatar_url||avatarFallback(p.username))}"><div><h3>${esc(p.username)}</h3><div class="small">Rating ${p.rating} · ⭐ ${p.points}</div></div></div><div class="notice">${esc(p.bio||'မိတ်ဆက်စာ မရှိသေးပါ')}</div><div class="small">W ${p.wins} · D ${p.draws} · L ${p.losses} · ${p.games_played} Games</div>${action}`)}catch(e){toast(humanError(e.code||e.message))}}
async function friendRequest(id){try{await Backend.social('friend_request',{player_id:id});toast('Friend request ပို့ပြီးပါပြီ');closeModal()}catch(e){toast(humanError(e.code||e.message))}}
async function friendAccept(id){try{await Backend.social('friend_accept',{friendship_id:id});toast('Friend ဖြစ်ပါပြီ');closeModal();loadFriends()}catch(e){toast(humanError(e.code||e.message))}}
async function openFriends(){if(!Backend.ready)return toast('Online account မချိတ်ရသေးပါ');showScreen('friends');await loadFriends()}
async function loadFriends(){try{const r=await Backend.social('friends'),all=r.friendships||[],req=all.filter(f=>f.status==='pending'&&f.addressee_id===Backend.user.id),accepted=all.filter(f=>f.status==='accepted');$("friendRequests").innerHTML=req.map(f=>`<div class="list-item"><img class="avatar" src="${esc(f.requester?.avatar_url||avatarFallback(f.requester?.username))}"><div class="grow"><b>${esc(f.requester?.username||'Player')}</b><div class="small">Rating ${f.requester?.rating??'—'}</div></div><button class="btn" style="max-width:80px" onclick="friendAccept('${f.id}')">လက်ခံ</button></div>`).join('')||'<div class="empty">Friend request မရှိပါ</div>';$("friendsList").innerHTML=accepted.map(f=>{const p=f.requester_id===Backend.user.id?f.addressee:f.requester;return `<div class="list-item"><img class="avatar" src="${esc(p?.avatar_url||avatarFallback(p?.username))}" onclick="openPlayer('${p.id}')"><div class="grow" onclick="openPlayer('${p.id}')"><b>${esc(p?.username||'Player')}</b><div class="small">Rating ${p?.rating??'—'}</div></div><button class="btn secondary" style="max-width:76px" onclick="openDM('${p.id}','${esc(p?.username||'Player')}')">💬</button><button class="btn" style="max-width:76px" onclick="chooseTime('invite','${p.id}')">🎮</button></div>`}).join('')||'<div class="empty">Friend မရှိသေးပါ</div>'}catch(e){toast(humanError(e.code||e.message))}}
async function searchPlayers(){if(!Backend.ready)return;const q=$("friendSearch").value.trim();try{const r=await Backend.social('players',{query:q});$("playerSearchResults").innerHTML=(r.players||[]).map(p=>`<div class="list-item"><img class="avatar" src="${esc(p.avatar_url||avatarFallback(p.username))}"><div class="grow"><b>${esc(p.username)}</b><div class="small">Rating ${p.rating} · W ${p.wins||0} / D ${p.draws||0} / L ${p.losses||0}</div></div><button class="btn secondary" style="max-width:85px" onclick="openPlayer('${p.id}')">Profile</button></div>`).join('')||'<div class="empty">Player မတွေ့ပါ</div>'}catch(e){toast(humanError(e.code||e.message))}}
async function openDM(id,name){closeModal();currentDMPlayer=id;$("messagePeer").textContent='💬 '+name;showScreen('messages');clearInterval(dmTimer);await loadDM();dmTimer=setInterval(loadDM,2000)}
async function loadDM(){if(!currentDMPlayer)return;try{const r=await Backend.social('messages',{player_id:currentDMPlayer});$("dmLog").innerHTML=(r.messages||[]).map(m=>`<div class="bubble ${m.sender_id===Backend.user.id?'me':'them'}">${m.kind==='sticker'?`<span style="font-size:27px">${esc(m.sticker)}</span>`:esc(m.body)}</div>`).join('');$("dmLog").scrollTop=$("dmLog").scrollHeight}catch(e){console.warn(e)}}
async function sendDM(){const v=$("dmInput").value.trim();if(!v)return;$("dmInput").value='';try{await Backend.social('send_message',{player_id:currentDMPlayer,body:v});loadDM()}catch(e){toast(humanError(e.code||e.message))}}
async function sendDMSticker(sticker){try{await Backend.social('send_message',{player_id:currentDMPlayer,kind:'sticker',sticker});loadDM()}catch(e){toast(humanError(e.code||e.message))}}
async function sendGameInvite(id,seconds){try{await Backend.social('send_invite',{player_id:id,time_limit_seconds:seconds});closeModal();toast('ကစားဖို့ ဖိတ်ခေါ်ပြီးပါပြီ')}catch(e){toast(humanError(e.code||e.message))}}
async function loadInvites(){if(!Backend.ready)return;try{const r=await Backend.social('invites'),arr=(r.invites||[]).filter(i=>i.recipient_id===Backend.user.id&&i.status==='pending'&&Date.parse(i.expires_at)>Date.now());$("inviteCard").classList.toggle('hidden',!arr.length);$("inviteList").innerHTML=arr.map(i=>`<div class="notice"><b>${esc(i.sender?.username||'Player')}</b> က ${Math.round(i.time_limit_seconds/60)} min ပွဲ ကစားဖို့ ဖိတ်ထားပါတယ်<div class="grid"><button class="btn green" onclick="acceptInvite('${i.id}')">လက်ခံမယ်</button><button class="btn red" onclick="declineInvite('${i.id}')">ငြင်းမယ်</button></div></div>`).join('')}catch(e){console.warn(e)}}
async function acceptInvite(id){try{const r=await Backend.social('accept_invite',{invite_id:id});$("inviteCard").classList.add('hidden');await Backend.openGame(r.game)}catch(e){toast(humanError(e.code||e.message))}}
async function declineInvite(id){try{await Backend.social('decline_invite',{invite_id:id});loadInvites()}catch(e){toast(humanError(e.code||e.message))}}
function renderStaticBoard(el,board,flip=false){el.innerHTML='';for(let vr=0;vr<8;vr++)for(let vc=0;vc<8;vc++){const r=flip?7-vr:vr,c=flip?7-vc:vc,p=board[r][c],sq=document.createElement('div');sq.className='square '+(((r+c)%2)?'dark':'light');if(p){const pe=document.createElement('div');pe.className='piece '+(p>0?'black':'white')+(isKing(p)?' king':'');if(isKing(p))pe.innerHTML='<span class="kingmark">♛</span>';sq.appendChild(pe)}el.appendChild(sq)}}
async function spectateGame(id){stopLobbyLoop();spectateGameId=id;showScreen('spectate');await refreshSpectate();clearInterval(spectateTimer);spectateTimer=setInterval(refreshSpectate,1800)}
async function refreshSpectate(){if(!spectateGameId)return;try{const r=await Backend.social('spectate',{game_id:spectateGameId}),g=r.game;$("spectateNames").innerHTML=`⚫ <b>${esc(g.black?.username||'Black')}</b> vs ⚪ <b>${esc(g.white?.username||'White')}</b> · ${Math.round(g.time_limit_seconds/60)} min`;renderStaticBoard($("spectateBoard"),g.board,false);$("spectateStatus").textContent=g.status==='active'?`${g.turn===1?'⚫ Black':'⚪ White'} အလှည့် · Move ${g.move_number||0}`:`ပွဲပြီးပါပြီ · ${g.result_type||''}`;if(g.status!=='active')clearInterval(spectateTimer)}catch(e){$("spectateStatus").textContent=humanError(e.code||e.message)}}
function stopSpectating(){clearInterval(spectateTimer);spectateTimer=null;spectateGameId=null;startLobbyLoop()}
async function openSpectatorReplay(){if(!spectateGameId)return;try{const r=await Backend.social('history',{game_id:spectateGameId}),moves=r.moves||[];replayState={boards:[Rules.initial(),...moves.map(m=>cloneBoard(m.board_after))],moves:moves.map(m=>`${m.move_number}. ${m.color===1?'Black':'White'}: ${(m.path||[]).map(x=>squareName(x.from)+(x.capture?'x':'-')+squareName(x.to)).join(' → ')}`),index:moves.length};showScreen('replay');renderReplay()}catch(e){toast(humanError(e.code||e.message))}}
function toggleGameChat(){if(Game.mode!=='online')return toast('Online လူကစားသမားပွဲမှာပဲ Chat သုံးနိုင်ပါတယ်');$("gameChatPanel").classList.toggle('hidden');if(!$("gameChatPanel").classList.contains('hidden')){loadGameChat();clearInterval(gameChatTimer);gameChatTimer=setInterval(loadGameChat,1800)}else{clearInterval(gameChatTimer)}}
async function loadGameChat(){if(Game.mode!=='online'||!Game.matchId)return;try{const r=await Backend.social('game_chat',{game_id:Game.matchId});$("gameChatLog").innerHTML=(r.messages||[]).map(m=>`<div class="bubble ${m.sender_id===Backend.user.id?'me':'them'}"><b>${esc(m.sender?.username||'Player')}</b><br>${m.kind==='sticker'?`<span style="font-size:27px">${esc(m.sticker)}</span>`:esc(m.body)}</div>`).join('');$("gameChatLog").scrollTop=$("gameChatLog").scrollHeight}catch(e){console.warn(e)}}
async function sendGameChat(){const v=$("gameChatInput").value.trim();if(!v)return;$("gameChatInput").value='';try{await Backend.social('send_game_chat',{game_id:Game.matchId,body:v});loadGameChat()}catch(e){toast(humanError(e.code||e.message))}}
async function sendGameSticker(sticker){try{await Backend.social('send_game_chat',{game_id:Game.matchId,kind:'sticker',sticker});loadGameChat()}catch(e){toast(humanError(e.code||e.message))}}
async function openLeaderboard(){if(!Backend.ready){toast("Online account မချိတ်ရသေးပါ");return}showScreen("leaderboard");await loadLeaderboard()}
async function loadLeaderboard(){const el=$("leaderboardList");el.innerHTML='<span class="spinner"></span>Loading...';try{const r=await Backend.api("leaderboard");el.className="";el.innerHTML=(r.players||[]).map((p,i)=>`<div class="list-item" onclick="openPlayer('${p.id}')"><div class="rankno">#${i+1}</div><div class="grow"><b>${esc(p.username)}</b><div class="small">W ${p.wins||0} · D ${p.draws||0} · L ${p.losses||0} · ${p.games_played||0} Games</div></div><div class="right"><b style="color:#ffd45c">${p.rating}</b><div class="small">⭐ ${p.points||0}</div></div></div>`).join("")||'<div class="notice">Player မရှိသေးပါ</div>'}catch(e){el.innerHTML='<div class="notice err">'+esc(humanError(e.code||e.message))+'</div>'}}
let currentTournamentId=null,currentTournamentData=null;
async function openTournaments(){if(!Backend.ready){toast("Online account မချိတ်ရသေးပါ");return}Backend.stopTournamentWatch();showScreen("tournaments");await loadTournaments()}
function tournamentCount(t){const x=t.tournament_players;return Array.isArray(x)&&x[0]?Number(x[0].count||0):Number(x?.count||0)}
async function loadTournaments(){const el=$("tournamentList");el.innerHTML='<div class="notice"><span class="spinner"></span>Loading...</div>';try{const r=await Backend.api("list_tournaments");el.innerHTML=(r.tournaments||[]).map(t=>{const cnt=tournamentCount(t),status=t.status==="open"?"🟢 Open":t.status==="running"?"⚔️ Running":t.status==="finished"?"🏆 Finished":"Closed";return `<div class="t-card"><div class="row"><div class="grow"><b>${esc(t.name)}</b><div class="small">Host: ${esc(t.creator?.username||"Player")} · ${cnt}/${t.max_players} Players · ${Math.round(t.time_limit_seconds/60)} min</div><span class="badge">${status}</span></div><button class="btn secondary" style="max-width:92px" onclick="viewTournament('${t.id}')">ကြည့်မယ်</button></div>${t.champion?.username?`<div class="notice ok">🏆 Champion: <b>${esc(t.champion.username)}</b></div>`:""}</div>`}).join("")||'<div class="notice">Tournament မရှိသေးပါ</div>'}catch(e){el.innerHTML='<div class="notice err">'+esc(humanError(e.code||e.message))+'</div>'}}
async function createTournament(){const name=$("tName").value.trim(),max=Number($("tMax").value),time=Number($("tTime").value);if(name.length<2){toast("Tournament နာမည်ထည့်ပါ");return}try{const r=await Backend.api("create_tournament",{name,max_players:max,time_limit_seconds:time});toast("Tournament ဖန်တီးပြီးပါပြီ");$("tName").value="";await viewTournament(r.tournament_id)}catch(e){toast(humanError(e.code||e.message))}}
async function joinTournament(id){try{await Backend.api("join_tournament",{tournament_id:id});toast("Tournament ဝင်ပြီးပါပြီ");await viewTournament(id)}catch(e){toast(humanError(e.code||e.message))}}
async function startTournament(id){try{await Backend.api("start_tournament",{tournament_id:id});toast("Tournament စတင်ပါပြီ");await viewTournament(id)}catch(e){toast(humanError(e.code||e.message))}}
async function viewTournament(id){currentTournamentId=id;showScreen("tournamentDetail");Backend.watchTournament(id);await refreshTournamentDetail()}
async function refreshTournamentDetail(silent=false){if(!currentTournamentId)return;const el=$("tournamentDetailContent");if(!silent)el.innerHTML='<div class="notice"><span class="spinner"></span>Loading...</div>';try{const r=await Backend.api("tournament_details",{tournament_id:currentTournamentId});currentTournamentData=r;const t=r.tournament,players=r.players||[],matches=r.matches||[],me=Backend.user.id,isMember=players.some(x=>x.user_id===me),isHost=t.created_by===me;const byRound={};for(const m of matches)(byRound[m.round_no]??=[]).push(m);let bracket="";for(const rn of Object.keys(byRound).map(Number).sort((a,b)=>a-b)){bracket+=`<div class="round-head">ROUND ${rn}${rn===t.rounds?" · FINAL":""}</div>`+byRound[rn].map(m=>{const mine=m.player1_id===me||m.player2_id===me;const enter=mine&&m.status==="active"&&m.game_id?`<button class="btn green" onclick="openTournamentGame('${m.game_id}')">ပွဲဝင်မယ်</button>`:"";return `<div class="match-card"><b>Match ${m.match_no}</b><div class="small">${esc(m.player1?.username||"TBD")} vs ${esc(m.player2?.username||"TBD")}</div><div class="small">${m.status}${m.winner?.username?" · Winner: "+esc(m.winner.username):""}</div>${enter}</div>`}).join("")}el.innerHTML=`<div class="card"><div class="title">🏆 ${esc(t.name)}</div><div class="notice">${t.status.toUpperCase()} · ${players.length}/${t.max_players} Players · ${Math.round(t.time_limit_seconds/60)} min · ${t.rounds} Rounds</div>${t.champion?.username?`<div class="notice ok">🏆 Champion: <b>${esc(t.champion.username)}</b></div>`:""}${t.status==="open"&&!isMember?`<button class="btn" onclick="joinTournament('${t.id}')">Tournament ဝင်မယ်</button>`:""}${t.status==="open"&&isHost?`<button class="btn green" onclick="startTournament('${t.id}')">ပြိုင်ပွဲ စတင်မယ်</button><div class="small">Player ${t.max_players} ယောက်ပြည့်မှ စတင်နိုင်ပါတယ်။ Rating အလိုက် seed ခွဲပေးမယ်။</div>`:""}</div><div class="card"><div class="title">👥 Players</div>${players.map((p,i)=>`<div class="list-item"><div class="rankno">${p.seed?"#"+p.seed:"•"}</div><div class="grow"><b>${esc(p.profile?.username||"Player")}</b><div class="small">Rating ${p.profile?.rating??"—"} · ${p.status}</div></div></div>`).join("")||'<div class="notice">Player မရှိသေးပါ</div>'}</div><div class="card"><div class="title">🧩 Bracket</div>${bracket||'<div class="notice">Tournament စတင်ပြီးမှ bracket ပေါ်ပါမယ်။</div>'}</div>`}catch(e){if(!silent)el.innerHTML='<div class="notice err">'+esc(humanError(e.code||e.message))+'</div>'}}
async function openTournamentGame(gameId){try{const r=await Backend.api("get_game",{game_id:gameId});await Backend.openGame(r.game)}catch(e){toast(humanError(e.code||e.message))}}
let __lastAndroidBack=0;
function activeScreenId(){return document.querySelector(".screen.active")?.id||"home"}
function handleAndroidBack(){
  if($("modal")?.classList.contains("show")){closeModal();return}
  const screen=activeScreenId();
  if(screen==="game"&&!$("gameChatPanel")?.classList.contains("hidden")){toggleGameChat();return}
  if(screen==="replay"){closeReplay();return}
  if(screen==="messages"){openFriends();return}
  if(screen==="tournamentDetail"){openTournaments();return}
  if(screen==="spectate"){stopSpectating();goHome();return}
  if(screen==="game"){leaveToHome();return}
  if(screen!=="home"){goHome();return}
  const now=Date.now();
  if(now-__lastAndroidBack<1800){window.Capacitor?.Plugins?.App?.exitApp?.();return}
  __lastAndroidBack=now;
  toast("App ထွက်ရန် Back ကို နောက်တစ်ကြိမ်နှိပ်ပါ");
}
function setupAndroidBackButton(){
  const appPlugin=window.Capacitor?.Plugins?.App;
  if(!appPlugin?.addListener)return;
  appPlugin.addListener("backButton",()=>handleAndroidBack());
}

window.addEventListener("beforeunload",()=>{if(Game.mode!=="online")Game.timer.stop()});
window.addEventListener("online",()=>{if(Backend.ready&&Backend.activeGameId)Backend.refreshGame(Backend.activeGameId)});
setupAndroidBackButton();
Backend.init().then(()=>{if(Backend.ready)startLobbyLoop()});
